version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: B1hUSzvTYKhMGtOTPK7RYUwriph84Ragh
before_build:
  - nuget restore ".\Hotel_Search.sln"
build:
  project: .\Hotel_Search.sln
  verbosity: minimal
test_script:
- ps: >-
    vstest.console.exe /inIsolation /Enablecodecoverage /TestAdapterPath:".\packages\xunit.runner.visualstudio.2.3.0\build\_common\" .\Hotel_Search_Test\bin\Release\Hotel_Search_Test.dll /Settings:CodeCoverage.runsettings

    $coverageFilePath = Resolve-Path -path "TestResults\*\*.coverage"

    $coverageFilePath = $coverageFilePath.ToString()

    if(Test-Path .\coverage.coveragexml){ rm .\coverage.coveragexml }

    ."C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe" analyze /output:coverage.coveragexml "$coverageFilePath"

    Push-AppveyorArtifact coverage.coveragexml

    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.Coveralls.exe").ToString()
    
    Write-Output $coveralls
    
    & $coveralls --dynamiccodecoverage -i coverage.coveragexml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths -o cov.json

    Push-AppveyorArtifact cov.json
